# Generated by Django 4.2.7 on 2024-04-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_formulario_usuario_delete_formularios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='formulario',
        ),
        migrations.CreateModel(
            name='Relaciona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.formulario')),
                ('id_perg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.pergunta')),
            ],
        ),
    ]
